### ISSUE TITLE
Offline Mode?

### ISSUE THREAD

**Issue by seanmtracey** [ftlabs/big-ft#18]
Our screens might not always find themselves in a place where an internet connection is stable/readily available. Could we use a combination of service workers/local storage to save the most recent content offline so that if a Big FT computer restarts, we can still bring up content without a network connection instead of showing a blank screen?

I've done a quick check and the images are around 120kb when converted to Base64, which we could store in local storage (assuming we still get the ~5mb of storage without permissions). I've not used service workers before, but it's my understanding we can deliver locally stored assets (Javascript/CSS/HTML) if we so wish. Every time we manage to get an update, we replace the stored content with the new content.

**Comment by JakeChampion** [comment]
I think we should do this. What do we think about waiting until we have gathered the data about our clients' digital signage systems to see if they can support service-workers? If they can't run service-workers then we can do this work at a later date.

**Comment by JakeChampion** [comment]
PR for this work #82

**Comment by JakeChampion** [comment]
Resolved via #82
