### ISSUE TITLE
Content not refreshing?

### ISSUE THREAD

**Issue by triblondon** [ftlabs/big-ft#4]
Reports from Christina Scott that the content is not updating on her laptop when she loads http://ftlabs-big-ft.herokuapp.com in Chrome.

**Comment by JakeChampion** [comment]
I believe this has been fixed. She may have an older version of the website, could we ask her to reload the page and see if the problem persists.

**Comment by JakeChampion** [comment]
I can confirm that http://big.ft.com/ and http://big-test.ft.com/ both have fresh content being added to the page.
