### ISSUE TITLE
Feature Request: Allow locale to be configured by the end-user

### ISSUE THREAD

**Issue by JakeChampion** [ftlabs/big-ft#60]
Problem: End-user can not override what locale the website to be displayed as.

Solution: Expose a query parameter which lets the end-user explicitly set the locale to be configured as.

**Comment by seanmtracey** [comment]
+1

**Comment by triblondon** [comment]
0

**Comment by triblondon** [comment]
(I wouldn't necessarily object to this feature but it feels like solving a problem for which a solution already exists, and which is native to the platform)

**Comment by seanmtracey** [comment]
Right now, we're tied to displaying BigFT exclusively in Chrome as the localisation API we're using to detect the timezone is only supported there. https://github.com/ftlabs/big-ft/blob/master/client/src/main.js#L422. By creating a user override, we open up the possibility of other modern/capable browsers being able to display Big FT (like Firefox, or Edge)
