### ISSUE TITLE
Youtube favicon appears in Chrome Tab

### ISSUE THREAD

**Issue by seanmtracey** [ftlabs/big-ft#61]
![big-ft-favicon](https://cloud.githubusercontent.com/assets/913687/12262848/84da25b8-b922-11e5-911e-44cef4df9851.png)

**Comment by JakeChampion** [comment]
I see no favicon

**Comment by seanmtracey** [comment]
Can't repeat outside of my Chrome and no favicon is defined in our markup. Putting it down to Chrome having a wobbly and being ridiculous with caching.
