### ISSUE TITLE
be able to select different FT homepages

### ISSUE THREAD

**Issue by railsagainstignorance** [ftlabs/big-ft#65]
i.e. not just the default UK homepage.: "is it possible to create a Big FT US with a little bit of work? Our issue is that our US colleagues aren't engaged with/keep turning off the screens as it isn't relevant to them"

**Comment by railsagainstignorance** [comment]
homepage == edition.

Also, raised question in #ft-next:

a question about different editions: FT.com currently proffers Asia, Europe, India, Middle East, US, UK, whilst Next proffers UK and International. Are there plans to increase the number of editions on Next, or stick with the two?

I ask, because we've been asked about putting content from the US edition onto big.ft.com, which currently uses v1/FT.com pages for its list of articles, the reason being that our US colleagues are switching off the big.ft.com displays due to lack of local/relevant content.

And if/when the day comes to switch from v1 pages, what can we expect Next (or UPP) will be offering for US readers?

**Comment by AdaRoseCannon** [comment]
Adds the edition parameter so that it can display the same front pages as next (Intl and UK)

Fixed by #74
