### ISSUE TITLE
Allow content from different editions

### ISSUE THREAD

**Issue by seanmtracey** [ftlabs/big-ft#68]
Currently, Big FT content reflects the content of the UK version of the FT, which isn't necessarily what customers/offices in other climates/continents/timezones want. If we created a way to select the international or region-specific versions, we broaden Big FTs appeal

**Comment by AdaRoseCannon** [comment]
Closed by #74

**Comment by AdaRoseCannon** [comment]
Duplicate of #65

**Comment by AdaRoseEdwards** [comment]
Duplicate of #65
