### ISSUE TITLE
Obtain screenshot from Manilla

### ISSUE THREAD

**Issue by seanmtracey** [ftlabs/big-ft#69]
Our Manilla offices have mentioned that they would like the time for Manilla to appear alongside the other clocks on Big FT. A Manilla clock _should_ already be inserted automatically, but might not be. Chase up a screenshot from someone in the Manilla offices running Big FT and examine what's going on.

**Comment by JakeChampion** [comment]
It turns out this was not an issue and is instead a request from Manilla to have their clock shown in the default set.
