### ISSUE TITLE
Splice company specific stories into the Top 3 news items

### ISSUE THREAD

**Issue by seanmtracey** [ftlabs/big-ft#72]

**Comment by AdaRoseCannon** [comment]
http://next-elastic.ft.com/v3_api_v2/item/_search?q=google&sort=_lastUpdatedDateTime:desc&size=1

**Comment by AdaRoseCannon** [comment]
https://next.ft.com/organisations/acb24d4d-efa1-3916-8985-59d868208053.json <= for twitter

**Comment by AdaRoseCannon** [comment]
Closed by #79
